# Site settings
author: Sumer Gaiwkad
title: SG-My-Soft-Dev-Journey
header-img: img/home-bg.png
email: sg.comparch@gmail.com
copyright_name: Sumer Gaiwkad
description: > # this means to ignore newlines until "baseurl:"
  My journey through software development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  RSigmaSG

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
